### PR TITLE
Made clearer icons, and white icons for black menu bar

### PR DESCRIPTION
**Pull request by omgmog**
Hey nice app!

I've made some new icons, and also some white icons for those using the dark menu bar in OS X.

demo

pokeunstable
pokeok
pokedown
pokeinit

I also bodged together some menu items to allow you to switch between the icon sets.

You might want to change that to a preference that saves.

### CODE REVIEW

**Comment by pboardman** [comment]
These icons are great! I'll look into making a setting that save the icons color between executions.

Thanks a lot for your contribution!

**Comment by pboardman** [comment]
I'll create the .app binary and create a release when I get home from work.

**Comment by pboardman** [comment]
I compiled the .app, when I launch it I have to do a manual refresh before the icon changes color. @omgmog is it the same for you?

**Comment by pboardman** [comment]
I found the problem and fixed it, I also gave you credit for your icons in the README! :)

**Comment by omgmog** [comment]
Good stuff. Yeah as I said my approach to adding menu items was a bit of a _[bodge](https://en.wiktionary.org/wiki/bodge)_.

Thanks for the credit :+1:

**Pull request merged**
